<?php declare(strict_types=1);

/*
 * Copyright (c) 2022 ReCodem Pvt Ltd All rights reserved
 */

use Codem\ContactUs\ViewModel\ContactUsDetails;
use Codem\ContactUs\Block\Customer\Contactus;
use Magento\Framework\Escaper;

/**
 * @var ContactUsDetails $contactUs
 * @var Contactus $block
 */

$contactUs = $block->getData('view_model');

/**
 * @var $escaper Escaper
 */

?>


<form class="contact" action="<?= $contactUs->getFormAction(); ?>" id="contact-form" method="post" data-hasrequired="<?= $escaper->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <div class="field name required">
            <label class="label" for="name"><span><?= $escaper->escapeHtml(__('Name')) ?></span></label>
            <div class="control">
                <input name="name" id="name" title="Name" value="" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $escaper->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email"
                       id="email"
                       title="Email"
                       value=""
                       class="input-text"
                       type="email"
                       data-validate="{required:true, 'validate-email':true}"
                       data-mage-init='{"mage/trim-input":{}}'
                />
            </div>
        </div>
        <div class="field telephone">
            <label class="label" for="telephone"><span><?= $escaper->escapeHtml(__('Phone Number')) ?></span></label>
            <div class="control">
                <input name="phone_number"
                       id="phone_number"
                       title="Phone Number"
                       value=""
                       class="input-text"
                       type="tel"
                       data-validate="{required:true, 'validate-number':true}"/>
            </div>
        </div>
        <div class="field comment required">
            <label class="label" for="comment"><span><?= $escaper->escapeHtml(__('Comment')) ?></span></label>
            <div class="control">
                <textarea name="comment" id="comment" title="Name" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
            </div>
        </div>
        <?= $block->getChildHtml('captcha') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Submit" class="action submit primary">
                <span>Submit</span>
            </button>
        </div>
    </div>
</form>


